#! /usr/bin/env bash
set -uvx
set -e
#ssh -i ~/settings/BookingGateway.pem ec2-user@ec2-3-27-129-13.ap-southeast-2.compute.amazonaws.com
ssh -i ~/settings/BookingGatewayDev.pem ec2-user@ec2-54-250-183-204.ap-northeast-1.compute.amazonaws.com
