#! /usr/bin/env bash
set -uvx
set -e
#ssh -i ~/settings/BookingGateway.pem ec2-user@ec2-54-252-239-24.ap-southeast-2.compute.amazonaws.com
ssh -i ~/settings/BookingGatewayDev.pem ec2-user@ec2-43-207-216-3.ap-northeast-1.compute.amazonaws.com
