#! /usr/bin/env bash
#set -uvx
#set -e
#cd "$(dirname "$0")"
#cwd=`pwd`
#ts=`date "+%Y.%m%d.%H%M.%S"`

if [ -z "$1" ]; then
  gh release list | sed 's/|/ /' | awk '{print $1, $8}'
else
  name="$1"
  gh release list | sed 's/|/ /' | awk '{print $1, $8}' | grep "$name.v"
fi
