//
// Auto-generated by dnne-gen
//
// .NET Assembly: SimpleApi
//

//
// Declare exported functions
//
#ifndef __DNNE_GENERATED_HEADER_SIMPLEAPI__
#define __DNNE_GENERATED_HEADER_SIMPLEAPI__

#include <stddef.h>
#include <stdint.h>
#ifdef DNNE_COMPILE_AS_SOURCE
    #include <dnne.h>
#else
    // When used as a header file, the assumption is
    // dnne.h will be next to this file.
    #include "dnne.h"
#endif // !DNNE_COMPILE_AS_SOURCE

// Computed from SimpleApi.Class1.add2
DNNE_EXTERN_C DNNE_API int32_t DNNE_CALLTYPE add2(int32_t a, int32_t b);

#endif // __DNNE_GENERATED_HEADER_SIMPLEAPI__

//
// Define exported functions
//
#ifdef DNNE_COMPILE_AS_SOURCE

#ifdef DNNE_WINDOWS
    #ifdef _WCHAR_T_DEFINED
        typedef wchar_t char_t;
    #else
        typedef unsigned short char_t;
    #endif
#else
    typedef char char_t;
#endif

//
// Forward declarations
//

extern void* get_callable_managed_function(
    const char_t* dotnet_type,
    const char_t* dotnet_type_method,
    const char_t* dotnet_delegate_type);

extern void* get_fast_callable_managed_function(
    const char_t* dotnet_type,
    const char_t* dotnet_type_method);

//
// String constants
//

#ifdef DNNE_TARGET_NET_FRAMEWORK
    static const char_t* t1_name = DNNE_STR("SimpleApi.Class1");
#else
    static const char_t* t1_name = DNNE_STR("SimpleApi.Class1, SimpleApi");
#endif // !DNNE_TARGET_NET_FRAMEWORK


//
// Exports
//

// Computed from SimpleApi.Class1.add2
static int32_t (DNNE_CALLTYPE* add2_ptr)(int32_t a, int32_t b);
DNNE_EXTERN_C DNNE_API int32_t DNNE_CALLTYPE add2(int32_t a, int32_t b)
{
    if (add2_ptr == NULL)
    {
        const char_t* methodName = DNNE_STR("add2");
        add2_ptr = (int32_t(DNNE_CALLTYPE*)(int32_t a, int32_t b))get_fast_callable_managed_function(t1_name, methodName);
    }
    return add2_ptr(a, b);
}

#endif // DNNE_COMPILE_AS_SOURCE
