#! /usr/bin/env bash
#set -uvx
set -e
#cd "$(dirname "$0")"
#cwd=`pwd`
#ts=`date "+%Y.%m%d.%H%M.%S"`
export PS1="\[\e]0;\w\a\]\n\[\e[32m\]\u@\h \[\e[35m\]$MSYSTEM\[\e[0m\] \[\e[33m\]\w\[\e[0m\]\n\$ "
bash.exe --norc --noprofile
