#! /usr/bin/env bash
# https://scrapbox.io/gosyujin/Zip%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E3%81%AE%E6%9A%97%E5%8F%B7%E5%8C%96%E6%96%B9%E5%BC%8F%E3%82%92%E8%AA%BF%E3%81%B9%E3%82%8B
7z.exe l -slt $1 | grep Method
